miniflux_api_token: 
miniflux_base_url: https://
# Set to the number of entries you want to return and filter on. Defaults to 100 (a Miniflux default). Make sure this number is higher than your average number of unread entries otherwise you'll just be running the script on the same entries each time the script runs (and you won't actually be filtering new entries at all).
miniflux_entries_limit: 10000
log_path: 
# Add regular expressions to the blocklist below:
blocklist_regex:
  - \$\d+
  - \b(\% off)\b
  - \b(\d+ best)\b
  - \b(accessories)\b
  - \b(app store)\b
  - \b(best deals)\b

